stages:
  - build
  - scan

build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn dependency:tree
      -DoutputFile=.debricked-maven-dependencies.tgf
      -DoutputType=tgf
  artifacts:
    paths:
      - .debricked-maven-dependencies.tgf
    expire_in: 1 day

debricked:
  stage: scan
  script:
    - curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
    - ./debricked scan
