language: java

jobs:
  include:
    - stage: Debricked-scan
      on:
        branch: "*"
      env:
        -  DEBRICKED_TOKEN=${DEBRICKED_TOKEN}
      before_install:
        - mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
        - curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
      cache:
        directories:
          - $HOME/.m2
      script: ./debricked scan
