# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp
  pod 'Alamofire', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'Kingfisher', '~> 7.0'

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 5.0'
    pod 'Nimble', '~> 10.0'
  end

  target 'TestAppUITests' do
    # Pods for testing
  end

end
