jobs:
  include:
    - stage: Debricked-scan
      on:
        branch: "*"
      env:
        -  DEBRICKED_TOKEN=${DEBRICKED_TOKEN}
      before_install: curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
      script: ./debricked scan
