name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions/scan@v3.0.1
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
