stages:
  - build
  - scan

build:
  stage: build
  image: gradle:alpine
  script:
    - sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
  artifacts:
    paths:
      - .debricked-gradle-dependencies.txt
    expire_in: 1 day

debricked:
  stage: scan
  script:
    - curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
    - ./debricked scan
