trigger:
  branches:
    include:
      - '*' # Run on all branches

resources:
  - repo: self

stages:
  - stage: debricked
    jobs:
      - job: debricked
        displayName: Debricked scan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
            displayName: './gradlew dependencies'

          - script: |
              env > env.list
              docker run -v $HOME:$HOME --env-file ./env.list debricked/scan
            displayName: Debricked scan
            env:
              DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)
