stages:
  - build
  - scan

build:
  stage: build
  image: go
  script:
    - printf "$(go mod graph)\n\n$(go list -mod=readonly -e -m all)" > .debricked-go-dependencies.txt
  artifacts:
    paths:
      - .debricked-go-dependencies.txt
    expire_in: 1 day

debricked:
  stage: scan
  script:
    - curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
    - ./debricked scan
