source 'https://rubygems.org'

ruby '~> 3.0'

# Web framework
gem 'rails', '~> 7.0'

# Database
gem 'pg', '~> 1.4'

# Server
gem 'puma', '~> 6.0'

# JSON processing
gem 'jbuilder', '~> 2.11'

# Authentication
gem 'devise', '~> 4.9'

# Authorization
gem 'pundit', '~> 2.3'

# Background jobs
gem 'sidekiq', '~> 7.0'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'pry-byebug', '~> 3.10'
end

group :development do
  gem 'rubocop', '~> 1.50', require: false
  gem 'rubocop-rails', '~> 2.19', require: false
end

group :test do
  gem 'simplecov', '~> 0.22', require: false
  gem 'webmock', '~> 3.18'
end
