name: Debricked scan

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: debricked/cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - run: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
      - run: debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
