steps:
  - label: ":go: go mod graph"
    command: |
      printf "$(go mod graph)\n\n$(go list -mod=readonly -e -m all)" > .debricked-go-dependencies.txt
    plugins:
      - golang#v2.0.0:
          version: 1.17
    artifact_paths: "**/.debricked-go-dependencies.txt"
  - wait
  - label: ":shield: Debricked"
    command:
      - buildkite-agent artifact download "**.debricked-go-dependencies.txt" .
      - curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
      - ./debricked scan
