steps:
  - label: ":maven: mvn dependency:tree"
    command: mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
    plugins:
      - docker#v5.3.0:
          image: maven
          workdir: /app
    artifact_paths: "**/.debricked-maven-dependencies.tgf"
  - wait
  - label: ":shield: Debricked"
    command:
      - buildkite-agent artifact download "**.debricked-gradle-dependencies.txt" .
      - curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
      - ./debricked scan
