name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push:
    name: 'Push Docker images'
    strategy:
      matrix:
        stage: [ 'cli', 'scan', 'resolution']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta - cli
        if: ${{ matrix.stage == 'cli' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=true
          images: |
            debricked/cli
            ghcr.io/debricked/cli
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge
            
      - name: Docker meta - other
        if: ${{ matrix.stage != 'cli' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=true
            suffix=${{ matrix.stage }},onlatest=true
          images: |
            debricked/cli
            ghcr.io/debricked/cli
          tags: |
            type=semver,pattern={{version}}-
            type=semver,pattern={{major}}.{{minor}}-
            type=semver,pattern={{major}}-
            type=edge-
            type=raw,value=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/docker/Dockerfile
          target: ${{ matrix.stage }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
