name: Debrickedz

on: [push]

jobs:
  scan_test:
    runs-on: ubuntu-latest
    container: debricked/cli:latest-resolution
    steps:
      - uses: actions/checkout@v3
      - run: apk -R info -vv
      - run: apk -R info -vv g++-12.2.1_git20220924-r10
      - run: apk list --installed
