name: Debrickedz

on: [push]

jobs:
  scan_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions@v3
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
      - run: apk -R info
      - run: apk -r info
